apiVersion: apps/v1
kind: Deployment
metadata:
  name: my-node-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app: node-app
  template:
    metadata:
      labels:
        app: node-app
    spec:
      containers:
        - name: node-app
          image: kushagrag99/my-app:01
          ports:
            - containerPort: 3000
        
---
apiVersion: v1
kind: Service
metadata:
  name: service-my-nodedb-app
spec:
  selector:
    app: nodedb-app
  ports:
    - name: http
      port: 8080
      targetPort: 3000
  type: LoadBalancer
